name: Build and deploy an app to AKS

on:
  push:
    tags:
      - '*'

env:
  AZURE_CONTAINER_REGISTRY: "anttest"
  CONTAINER_NAME: "flask-app"
  RESOURCE_GROUP: "ant-test-rg"
  CLUSTER_NAME: "ant-test-cluster"
  DEPLOYMENT_MANIFEST_PATH: "k8s/flask-app.yaml"

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Get tags
      - name: Get tags
        run: |
          git fetch --tags
          echo "TAGS=$(git describe --abbrev=0 --tags)" >> "$GITHUB_ENV"

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
            az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.TAGS }} --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Get tags
      - name: Get tags
        run: |
          git fetch --tags
          echo "TAGS=$(git describe --abbrev=0 --tags)" >> "$GITHUB_ENV"

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      # Replace Application Insights connection string in the manifest file
      - name: Replace connection string
        run: |
          sed -i "s|securestring-value|${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}|g" ${{ env.DEPLOYMENT_MANIFEST_PATH }}

      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.TAGS }}
